{{- if and .Values.config.create (not .Values.config.existingSecret) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "queryflux.configMapName" . }}
  labels:
    {{- include "queryflux.labels" . | nindent 4 }}
data:
  {{ .Values.config.fileName }}: |
{{ tpl (toYaml .Values.config.data) . | nindent 4 }}
{{- end }}
